stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install --legacy-peer-deps
    - npx prettier --write .
    - npm install ajv --save-dev --legacy-peer-deps
    - npm run build
  only:
    - main
  artifacts:
    paths:
      - ./build

deploy:
  stage: deploy
  script:
    - cp -rf ./build/* /usr/share/nginx/mindcom-pay-new
  only:
    - main
